#!/usr/bin/env bash
# Loops from 1 to 10 and displays:
#   "bad luck" for the 4th iteration
#   "good luck" for the 8th iteration
#   "Best School" for all other iterations

l=0

while [ $l -lt 10 ]
do
  if [ $l -eq 3 ]
  then
    echo "bad luck"
  elif [ $l -eq 7 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  (( l++ ))
done
